# Generated by Django 5.1.3 on 2024-12-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TennisPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('serve', models.IntegerField(help_text='Serve ability rating (0-100)')),
                ('forehand', models.IntegerField(help_text='Forehand ability rating (0-100)')),
                ('backhand', models.IntegerField(help_text='Backhand ability rating (0-100)')),
                ('volley', models.IntegerField(help_text='Volley ability rating (0-100)')),
                ('stamina', models.IntegerField(help_text='Stamina ability rating (0-100)')),
                ('agility', models.IntegerField(help_text='Agility ability rating (0-100)')),
            ],
            options={
                'verbose_name_plural': 'Tennis Players',
                'ordering': ['-serve'],
            },
        ),
    ]
