# Generated by Django 5.1.3 on 2025-02-05 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tennisplayer_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tennisplayer',
            old_name='username',
            new_name='creator_username',
        ),
        migrations.RemoveField(
            model_name='userproperties',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='userproperties',
            name='favorite_players',
        ),
        migrations.AddField(
            model_name='tennisplayer',
            name='current_player',
            field=models.ManyToManyField(related_name='current_player_for_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tennisplayer',
            name='favorite_player',
            field=models.ManyToManyField(related_name='favorite_player_for_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='isonline',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='rankpoints',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
