# Generated by Django 5.1.3 on 2024-12-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customtennisplayer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisplayer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
