# Generated by Django 5.1.3 on 2025-02-05 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friendship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tennisplayer',
            name='current_player',
        ),
        migrations.AddField(
            model_name='userproperties',
            name='current_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_player_for_profile', to='api.tennisplayer'),
        ),
        migrations.RemoveField(
            model_name='tennisplayer',
            name='favorite_player',
        ),
        migrations.AddField(
            model_name='tennisplayer',
            name='favorite_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_player_for_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
