# Generated by Django 5.1.3 on 2024-12-07 19:17

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tennisplayer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tennisplayer',
            options={'ordering': ['id'], 'verbose_name_plural': 'Tennis Players'},
        ),
        migrations.AddField(
            model_name='tennisplayer',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='UserProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isonline', models.BooleanField(blank=True, null=True)),
                ('friends', models.CharField(max_length=250)),
                ('customplayers', models.CharField(max_length=250)),
                ('favoriteplayers', models.CharField(max_length=250)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registered user',
                'ordering': ['-user_name'],
            },
        ),
    ]
