# Generated by Django 5.1.3 on 2025-02-05 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_friendship_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennisplayer',
            name='favorite_player',
        ),
        migrations.AddField(
            model_name='tennisplayer',
            name='favorite_player',
            field=models.ManyToManyField(related_name='favorite_player_for_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
