# Generated by Django 5.1.3 on 2024-12-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tennisplayer_options_tennisplayer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisplayer',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
