# Generated by Django 5.1.3 on 2024-12-17 11:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tennisplayer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tennisplayer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userproperties',
            options={'ordering': ['-username'], 'verbose_name_plural': 'Registered user'},
        ),
        migrations.RenameField(
            model_name='tennisplayer',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userproperties',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='tennisplayer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='agility',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='backhand',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='forehand',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='serve',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='stamina',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='volley',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='CustomTennisPlayer',
        ),
    ]
