# Generated by Django 5.1.3 on 2024-12-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tennisplayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperties',
            name='rankpoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tennisplayer',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
