# Generated by Django 5.1.3 on 2026-03-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_username_profile_user_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_image',
            field=models.CharField(choices=[('user1.png', 'Avatar 1'), ('user2.png', 'Avatar 2'), ('user3.png', 'Avatar 3'), ('user4.png', 'Avatar 4'), ('user5.png', 'Avatar 5'), ('user6.png', 'Avatar 6'), ('user7.png', 'Avatar 7'), ('user8.png', 'Avatar 8'), ('user9.png', 'Avatar 9'), ('user10.png', 'Avatar 10')], default='user1.png', max_length=20),
        ),
    ]
