# Generated by Django 5.1.3 on 2026-03-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproperties',
            options={'ordering': ['-user'], 'verbose_name_plural': 'UserProperties'},
        ),
        migrations.RenameField(
            model_name='userproperties',
            old_name='username',
            new_name='user',
        ),
    ]
