# Generated by Django 5.1.3 on 2026-03-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
