# Generated by Django 5.1.3 on 2026-03-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='current_player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_player_for_profile', to='api.tennisplayer'),
        ),
    ]
