# Generated by Django 5.1.3 on 2026-03-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_userproperties_current_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='current_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_player_for_profile', to='api.tennisplayer'),
        ),
    ]
