# Generated by Django 5.1.3 on 2026-03-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
