# Generated by Django 5.1.3 on 2026-03-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
